### ISSUE TITLE
Solar Monitor

### ISSUE THREAD

**Issue by gokulshriyam** [bittailor/BtSolarMonitor#1]
Thanks for making such monitor board

I'm going to make a solar monitor board as part of my graduation project at college..!
Could you help me in redesigning this board again ?

I wanna to remove actuators, GSM module and inbuilt display system.

I want to measure inverter's measurement (Generation), Battery's measurement, Consumption measurement (load)  -   For ONGRID 

I want to include ESP8266 feather to this board and make it WiFi enabled and API connected to thingspeak.

Could you help me in this regard ?

**Comment by bittailor** [comment]
I'm not able to provide you support to design the monitor board for your graduation project. Feel free to fork my board design and adapt to your needs if it helps you. As far as I understood you would even remove most of the parts beside the current  monitor chips so it might be even simpler to start from scratch.

Also be aware that my board is not designed for large currents (max 10A) and voltages (max 15V). If you design a board for on grid system with inverters, chances are that you have to deal with larger currents and voltages and then the INA129 chip might not be the appropriate, you might need a Hall-Effect based sensor.
